### ISSUE TITLE
Not able to retrieve single types

### ISSUE THREAD

**Issue by sebastiancretu** [strapi/jekyll-strapi#14]
I've set the config file with the single type collection like this:

```
strapi:
    # Your API endpoint (optional, default to http://localhost:1337)
    endpoint: http://localhost:1337
    collections:
         aboutme:
                type: about-me
```

Unfortunatelly, if I do ```{{ strapi.collections.aboutme | inspect }}``` in the template, the result that I get is an empty array even though I can see in the terminal that the request was made: ``` Jekyll Strapi: Fetching entries from http://localhost:1337/about-me?_limit=10000```

I would expect for this to be working too and retrieve all the fields/values on the single types also. Is this possible ?
