### ISSUE TITLE
Address not available on Dev Jekyll build using Docker Compose

### ISSUE THREAD

**Issue by oDinZu** [strapi/jekyll-strapi#17]
### **Error**

```
Jekyll Strapi: Fetching entries from http://localhost:1337/testdata?_limit=10000
jekyll-serve_1  | /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to localhost:1337 (Address not available - connect(2) for "localhost" port 1337) (Errno::EADDRNOTAVAIL)
```

**Jekyll Version:** 4.2.0

Viewing from web browser locally, I see: 

http://localhost:1337/posts

```
id | 2
title | "Title is long enough now"
published_at | "2021-07-29T23:12:33.002Z"
created_at | "2021-07-29T23:05:14.623Z"
updated_at | "2021-07-29T23:12:33.014Z"
```
### **Jekyll Layout:** 
```
<!-- This loops through the Strapi posts -->
{%- if strapi.collections.posts.size > 0 -%}
      <ul>
        {%- for post in strapi.collections.posts -%}
        <li>
          {{ post.name }}
        </li>
        {%- endfor -%}
      </ul>
  {%- endif -%}
```
### **Jekyll Config**
```
# Strapi dashboard integration
strapi:
    # Your API endpoint (optional, default to http://localhost:1337)
    endpoint: http://localhost:1337
    # Collections, key is used to access in the strapi.collections
    # template variable
    collections:
        # Example for a "posts" collection
        posts:
            type: posts
```

### **Jekyll Gemfile**

```
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.12"
   gem "jekyll-strapi", "~> 0.1.3"
end
```
