### ISSUE TITLE
Permalinks broken - Strapi v4

### ISSUE THREAD

**Issue by oDinZu** [strapi/jekyll-strapi#22]
I am unable to have my strapi collection output a proper permalink. 

I tested all kinds of :settings, but initially I thought /blog/:title would use the strapi [field] title for each post. 

The api is working and I also have slugify setup to maybe use :slug. 

The permalink /blog/:categories/:year/:month/:day/:title/ is what I used with Jekyll before removing my collections for Strapi integration.

**_config.yml**
```
strapi:
    # Your API endpoint (optional, default to http://localhost:1337)
    endpoint: https://localhost:1337
    # Collections, key is used to access in the strapi.collections
    # template variable
    collections:
        # Example for a "posts" collection
        posts:
            # Collection name (optional). Used to construct the url requested. Example: type `foo` would generate the following url `http://localhost:1337/foo`.
            type: posts
            # Permalink used to generate the output files (eg. /posts/:id).
            permalink:/blog/:categories/:year/:month/:day/:title/
            layout: post.html
            output: true
        authors:
            type: authors
```
