### ISSUE TITLE
Jekyll and Strapi: The Strapi server sent a error with the following status: 404. Please make sure it is correctly running

### ISSUE THREAD

**Issue by stephan9696** [strapi/jekyll-strapi#6]
I am currently trying to follow this tutorial (https://blog.strapi.io/building-a-static-website-using-jekyll-and-strapi/) and everything was working fine until the "Posts List" step. Once I added the _layouts/home.html file, changed _config.yml and restarted the jekyll server (bundle exec jekyll serve), I ended up with an error message:

> jekyll 3.8.5 | Error: The Strapi server sent a error with the following status: 404. Please make sure it is correctly running.

Thing is, the strapi server IS RUNNING... I have access to the the strapi admin backend and I can access and view the Posts json object by visiting: http://localhost:1337/posts.

**Comment by lauriejim** [comment]
Hello!
I think you have to add data before.

**Comment by ilearnbydoing** [comment]
I fixed 404 error now I am getting this error jekyll 3.8.6 | Error:  Can't convert Fixnum into String.

any help.
thanks

**Comment by michal-keidar** [comment]
How did you fix the 404 error?

**Comment by jeremylynch** [comment]
To fix the 404 your collection type must be pluralised, eg. "articles" rather than "article"

```yml
strapi:
    # Your API endpoint (optional, default to http://localhost:1337)
    endpoint: http://localhost:1337
    # Collections, key is used to access in the strapi.collections
    # template variable
    collections:
        # Example for a "articles" collection
        articles:   
            type: articles
```
